### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by urbie-mk2** [pimoroni/vl53l1x-python#2]
@Gadgetoid
Do you get correct values? Whenever I call getDistance I get values above 2meters. If I remove VL53L1_ClearInterruptAndStartMeasurement(dev); call from getDistance the values are good (except some few 3 - 5cm offset).

**Comment by Gadgetoid** [comment]
It appears not- comparing the range of values I get from the sensor with an actual ruler suggests it's quite far off the mark.

I suspect there's some part of the init or polling process that I am missing since I'm reading 0mm at about 7cm away from the sensor. Apart from being hopelessly wrong, the values are pretty stable though, which is promising.

Back to the datasheet/manual!

**Comment by Gadgetoid** [comment]
Okay I've dug down into the code and realised the problem is most likely with `VL53L1_WaitValueMaskEx` which should implement a wait on a register using a mask and is currently unimplemented. I'm looking into it.

**Comment by Gadgetoid** [comment]
I've pushed up a suite of fixes that should include correcting this measurement error: https://github.com/pimoroni/vl53l1x-python/commits/master

My test- `test.py` - is now giving me pretty good readings, although I'm testing against a smallish cardboard box and using steel ruler for distance confirmation and the readings get quite dicey at more than 50-60cm range depending on the size of my target.

**Comment by urbie-mk2** [comment]
@Gadgetoid
Thanks a lot for inquiring, I will test it tomorrow as well.

**Comment by urbie-mk2** [comment]
@Gadgetoid 
I have just tested the fixes and they work much better now. 

At 10cm with Long range mode, natural daylight, no sun, no room light  it was pretty precise, even at 4m.
